#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

SELECTED_THEMES = [
  'Atom One Light',
  'Ayu',
  'Community Material',
  'Default',
  'Github',
  'Gruvbox',
  'Learn with Sumit',
  'Material',
  'Monokai Pro',
  'Netbeans Light',
  'Night Owl',
  'Tiny Light',
  'Tokyo Night',
  'Visual Studio C/C++',
  'Winter is Coming',
].freeze

def process(results)
  selects = SELECTED_THEMES.map do |theme|
    results.find { |result| result['analyze'] == 'light' && result['theme'] == theme }
  end.sort_by { |result| result['average_cct'] }

  [
    ['themes',                          *selects.map { |select| select['theme'] }],
    ['index',                           *1.upto(selects.size).to_a],
    ['average_ccts',                    *selects.map { |select| select['average_cct'] }],
    ['average_ccts_without_background', *selects.map { |select| select['average_cct_without_background'] }],
    ['background_ccts',                 *selects.map { |select| select['background_cct'] }]
  ].map { |rows| rows.join(',') }.join("\n")
end

def main
  puts process(JSON.parse(ARGF.read))
end

main
