#!/usr/bin/env ruby
# frozen_string_literal: true

require 'csv'
require 'json'

def process(results)
  fields = results.first.keys
  index  = fields.index('cct')

  rows = results.map(&:values).sort_by { |row| [row[index]] }

  [fields, *rows].map(&:to_csv).join
end

def main
  puts process(JSON.parse(ARGF.read))
end

main
