#!/usr/bin/env ruby
# frozen_string_literal: true

require 'csv'
require 'yaml'

def process(results)
  fields = results.first.keys
  index  = fields.index('installs')

  rows = results.reject { |result| result['extension'].nil? }.map(&:values).sort_by { |row| [row[index]] }.reverse

  [fields, *rows].map(&:to_csv).join
end

def main
  puts process(YAML.load(ARGF.read))
end

main
