#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

require 'bdf'

def calculate!(hash)
  hash[:bits] = (hash[:bitmap] || []).map do |string|
    string.scan(/../).map { |pair| ("%08B" % pair.hex) }.join
  end

  return hash if hash[:bits].nil? || hash[:bits].empty?

  # TODO: Ampirik değerler
  # En geniş karakterler (örneğin 'm') 7 pixel, 1'er pixel yanlarda boş alsak 7 + 1 + 1 = 9
  # En yüksek karakterler (örneğin '|') 14 pixel, 1'er pixel üst altta boş alsak 14 + 1 + 1 = 16
  # Yüksekliği line-height oranında arttır 16 x 19/14 ~ 22
  hash[:nrows]    = 22
  hash[:ncols]    = 9

  hash[:areafull] = hash[:nrows] * hash[:ncols]
  hash[:count1]   = hash[:bits].sum { |row| row.count('1') }
  hash[:count0]   = hash[:areafull] - hash[:count1]

  hash
end

def process(font)
  result = {}
  font.instance_variable_get('@chars').each do |code, data|
    result[code.hex.chr(Encoding::UTF_8)] = calculate!(data)
  end
  result
end

def main
  puts JSON.pretty_generate process(BDF::Font.from_file(ARGV.empty? ? '/dev/stdin' : ARGV.first))
end

main
