#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates a JSON IR (Intermediate Representation) of BDF font
#
# Input:  BDF font
# Output: BDF JSON IR

require 'json'

require 'bdf'

def area_by_bbx(hash)
  hash[:bbx][:w] * hash[:bbx][:h]
end

def area_by_bits(hash)
  return 0 if hash[:bits].nil? || hash[:bits].first.nil?

  hash[:bits].size * hash[:bits].first.size
end

def calculate!(hash)
  hash[:bits] = (hash[:bitmap] || []).map do |string|
    string.scan(/../).map { |pair| ("%08B" % pair.hex) }.join
  end

  return hash if hash[:bits].nil? || hash[:bits].empty?

  hash[:nrows]    = hash[:bits].size
  hash[:ncols]    = hash[:bits].first.size
  hash[:areafull] = hash[:bits].size * hash[:bits].first.size
  hash[:areabbox] = hash[:bbx][:w] * hash[:bbx][:h]
  hash[:count1]   = hash[:bits].sum { |row| row.count('1') }
  hash[:count0]   = hash[:areafull] - hash[:count1]

  hash
end

def process(font)
  result = {}
  font.instance_variable_get('@chars').each do |code, data|
    result[code.hex.chr(Encoding::UTF_8)] = calculate!(data)
  end
  result
end

def main
  puts JSON.pretty_generate process(BDF::Font.from_file(ARGV.empty? ? '/dev/stdin' : ARGV.first))
end

main
