#!/usr/bin/env python3

import json
import logging
import os
import sys

from common import hex_to_cct,process

def main():
    if 'DEBUG' in os.environ:
        logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)

    if not sys.argv[1:]:
        content = sys.stdin.read()
    else:
        with open(sys.argv[1]) as f:
            content = f.read()

    data = json.loads(content)
    print(json.dumps(process(data), indent = 2, sort_keys = True))

main()
