#!/usr/bin/env ruby
# frozen_string_literal: true

require 'htmlbeautifier'

def process(content)
  content.force_encoding('UTF-16LE').encode!('UTF-8')
  content.gsub!(/^.*(<html>.*)$/mu, '\1')

  HtmlBeautifier.beautify(content)
end

def main
  puts process(ARGF.read)
end

main
