#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

def main
  rows = ARGV.map do |result_file|
    result = JSON.parse File.read(result_file)
    source = result['source']
    source['average_cct'] = result['average_cct'].round
    source['average_cct_without_background'] = result['average_cct_without_background'].round
    source['diff65'] = result['diff65'].round
    source['background_cct'] = result['background_cct'].round
    source
  end.sort_by { |row| [row['average_cct']] }

  puts JSON.pretty_generate rows
end

main
